version: '3.3'

networks:
  kafka_cluter:
    name: kafka_cluter
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.2
    user: root:root
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka_cluter

  kafka1:
    image: bitnami/kafka:3.6.1
    container_name: kafka1
    user: root:root
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '19092:19092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://127.0.1.1:19092
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://127.0.1.1:19092,INTERNAL://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
    networks:
      - kafka_cluter

  kafka2:
    image: bitnami/kafka:3.6.1
    container_name: kafka2
    user: root:root
    ports:
      - '9093:9093'
      - '19093:19093'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://127.0.1.1:19093,INTERNAL://:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_LISTENERS=INTERNAL://:9093,EXTERNAL://127.0.1.1:19093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka_cluter

  kafka3:
    image: bitnami/kafka:3.6.1
    container_name: kafka3
    user: root:root
    ports:
      - '9094:9094'
      - '19094:19094'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://127.0.1.1:19094,INTERNAL://:9094
      - KAFKA_LISTENERS=INTERNAL://:9094,EXTERNAL://127.0.1.1:19094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka_cluter
